### ISSUE TITLE
App crashing when decline authentication on uae pass or click cancel option in uae pass dialog webview in android, ios working fine

### ISSUE THREAD

**Issue by amitkumartiwaridis** [Faisalkc4u/uae_pass#8]
D/AndroidRuntime(16201): Shutting down VM
E/AndroidRuntime(16201): FATAL EXCEPTION: main
E/AndroidRuntime(16201): Process: com.dis.sharafexchange, PID: 16201
E/AndroidRuntime(16201): java.lang.NullPointerException
E/AndroidRuntime(16201): at ae.sdg.libraryuaepass.UAEPassAuthenticationDialog$initView$1.shouldOverrideUrlLoading(UAEPassAuthenticationDialog.kt:123)
E/AndroidRuntime(16201): at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:83)
E/AndroidRuntime(16201): at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(chromium-TrichromeWebViewGoogle6432.aab-stable-642216533:129)
E/AndroidRuntime(16201): at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime(16201): at android.os.MessageQueue.next(MessageQueue.java:350)
E/AndroidRuntime(16201): at android.os.Looper.loopOnce(Looper.java:187)
E/AndroidRuntime(16201): at android.os.Looper.loop(Looper.java:368)
E/AndroidRuntime(16201): at android.app.ActivityThread.main(ActivityThread.java:8848)
E/AndroidRuntime(16201): at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(16201): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
E/AndroidRuntime(16201): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049) @Faisalkc4u @abubakarmvp @faisalkcmvp

**Comment by faisalkcmvp** [comment]
Can you please provide a sample code
